### ISSUE TITLE
About the preprocessed data(FlyingThings3D)

### ISSUE THREAD

**Issue by lizhiqihhh** [yairkit/flowstep3d#2]
Hi, Yairkit, hope you are doing well. I have some issues related to the dataset.

-  I was trying to download the raw data and pre-process them, unfortunately, the disk space of my computer is full when I unzip some of the tar.gz files. May I ask can you provide the processed data online if it's not gigantic?

- I also tried to change data/loaders/flyingthings3d_subset.py in your source code to load the pre-processed data provided in the **FlowNet3D repo.** But I encountered another problem when I run the command: `python run.py -c configs/train/flowstep3d_self_ft.yaml`.  It stopped at epoch 0, throws an error: OSError: [Error 5 ] Input/output error. The data loader did load the point cloud as it almost loaded 55% of the data
- Do you have code to train on the preprocessed data provided by Flownet3D?

Looking forward to your kind reply. Many thanks！

**Comment by yairkit** [comment]
Hi @lizhiqihhh, thanks for your interest.

- Unfortunatlly I don't have the pre-processed data (it was on the servers of my previous institution).
- Regarding FlowNet3D data format - it's very similar, but as far as I remember they use the full frames, together with occlusion masks, where our format (following HPL) the occluded points being ignored at the pre-process step. 
- I don't have a code for FlowNet3D data format, but taking their DataLoader together with their pre-process data and integrate it into this env would be the easiest, I guess.

Good Luck!

**Comment by lizhiqihhh** [comment]
Hi @yairkit. Thank you very much for your reply~
