### ISSUE TITLE
can you provide pretrained mdoel of flyingthings3d? 

### ISSUE THREAD

**Issue by gxd1994** [yairkit/flowstep3d#3]
I use your code to train and can only get a result of 0.053 epe3d in flyingthings3d ?

**Comment by yairkit** [comment]
That's very strange.
Anyway, regarding pretrained weights, as mentioned in "Pretrained models" section of the README file:

In order to download pre-trained models, please run:
`bash scripts/download_models.sh`

**Comment by gxd1994** [comment]
I downloaded the model you provided and tested it on flything3d. The epe3d is only 0.052，but 0.045 in paper

**Comment by yairkit** [comment]
I assume you are using
configs/test/flowstep3d_sv.yaml file
and changed 'data' from 'kitti' to 'flyingthings3d'

Indeed, I can see that few hyperparams in this file are the optimal for the kitti benchmark.

please try to change:
`model_params:
  loc_flow_nn: 18
  loc_flow_rad: 1.5`

to:
`model_params:
  loc_flow_nn: 20
  loc_flow_rad: 2.5`

and make sure the checkpoint you're using is
'checkpoints/flowstep3d_sv/2020-10-19_13-17/epoch=33.ckpt' (it's the default in this file)


please let me know if it works for you.
thanks and sorry for the inconvenience.

**Comment by gxd1994** [comment]
yes, it works. thanks!
