### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by davezdeng8** [yairkit/flowstep3d#4]
In Figure 2 of the paper, there is a plot with the memory requirements of FlowStep3D, along with various other methods. Is this done with batch size 1? And can you share the values of these memory requirements? Thanks!

**Comment by yairkit** [comment]
Yes, it was done using BS=1, in 'test' mode (no grads).
```
FlowNet3D: 1.2GB
FlowStep3D (Ours): 1.3GB
pointPWC: 1.9GB
FLOT: 4.5GB
HPLFlow: 10.7GB
```

**Comment by davezdeng8** [comment]
One more question, what's the training memory requirement? Additionally, what's the inference runtime, and on what platform/hardware is this runtime achieved?
